import React from 'react';

interface LegalModalProps {
  type: 'privacy' | 'terms' | 'about' | 'contact' | null;
  onClose: () => void;
}

export const LegalModals: React.FC<LegalModalProps> = ({ type, onClose }) => {
  if (!type) return null;

  const content = {
    privacy: {
      title: "Privacy Policy",
      body: "At Velvet Runway, we value your privacy. We use Google AdSense to serve advertisements. These vendors use cookies to serve ads based on your prior visits. You may opt out of personalized advertising by visiting Ads Settings. We do not store personal identifiable information on our servers; all AI-generated interactions are processed in real-time."
    },
    terms: {
      title: "Terms of Service",
      body: "By accessing Velvet Runway, you agree to our terms. This site features AI-generated fashion imagery intended for editorial and artistic inspiration. Users must be 18+. Redistribution of AI assets without attribution is prohibited. Content is generated by Google Gemini models."
    },
    about: {
      title: "About The Agency",
      body: "Velvet Runway is a premier AI-driven fashion showcase. Our proprietary AI Agency Manager curates daily high-fashion collections using state-of-the-art neural networks. We bridge the gap between technology and haute couture."
    },
    contact: {
      title: "Contact Us",
      body: "For partnership inquiries, DMCA notices, or technical support, please contact: agency@velvetrunway.ai. Our team responds to all verified inquiries within 48 hours."
    }
  };

  const active = content[type];

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/90 backdrop-blur-sm">
      <div className="max-w-2xl w-full bg-[#111] border border-[#d4af37]/30 rounded-2xl p-8 shadow-[0_0_50px_rgba(0,0,0,1)] relative animate-in fade-in zoom-in duration-300">
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 text-neutral-500 hover:text-[#d4af37] transition-colors"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-6 h-6">
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
        <h2 className="text-3xl font-bold serif text-[#d4af37] mb-6 gold-glow">{active.title}</h2>
        <div className="text-neutral-300 leading-relaxed space-y-4 text-sm max-h-[60vh] overflow-y-auto pr-4 custom-scrollbar">
          <p>{active.body}</p>
          <p className="text-neutral-500 italic mt-8 border-t border-white/5 pt-4">Last Updated: {new Date().toLocaleDateString()}</p>
        </div>
        <button 
          onClick={onClose}
          className="mt-8 w-full bg-[#d4af37] text-black font-bold uppercase py-3 rounded-lg tracking-widest hover:bg-[#f9e29f] transition-all"
        >
          Close Document
        </button>
      </div>
    </div>
  );
};