import React, { useState, useCallback } from 'react';
import { ModelProfile, RevealStage } from '../types';

interface ModelCardProps {
  model: ModelProfile;
  onUpdate: (id: string, updates: Partial<ModelProfile>) => void;
}

export const ModelCard: React.FC<ModelCardProps> = ({ model, onUpdate }) => {
  const [isHovered, setIsHovered] = useState(false);

  const handleNextStage = useCallback(() => {
    // Zero-token interaction: All images were pre-generated by the AgencyManager orchestrator
    let nextStage = model.stage;
    if (model.stage === RevealStage.FullyClothed) nextStage = RevealStage.SummerOutfit;
    else if (model.stage === RevealStage.SummerOutfit) nextStage = RevealStage.Bikini;
    else nextStage = RevealStage.FullyClothed;

    const preGeneratedUrl = model.stageImages[nextStage];
    if (preGeneratedUrl) {
      onUpdate(model.id, { 
        stage: nextStage, 
        imageUrl: preGeneratedUrl 
      });
    }
  }, [model, onUpdate]);

  return (
    <div 
      className="relative group w-full aspect-[3/4] rounded-xl overflow-hidden shadow-2xl transition-all duration-500 hover:scale-[1.02] bg-neutral-900 border border-white/5"
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onClick={handleNextStage}
    >
      <img 
        src={model.imageUrl} 
        alt={model.name}
        key={model.imageUrl}
        className="w-full h-full object-cover transition-opacity duration-700"
      />

      <div className={`absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent transition-opacity duration-300 flex flex-col justify-end p-6 ${isHovered ? 'opacity-100' : 'opacity-0'}`}>
        <h3 className="text-2xl font-bold text-white serif mb-1 gold-glow uppercase tracking-tight">{model.name}</h3>
        <p className="text-neutral-400 text-[10px] mb-4 line-clamp-2 leading-relaxed uppercase tracking-widest">{model.description}</p>
        
        <div className="flex gap-2">
          <button 
            className="flex-1 bg-white/10 backdrop-blur-md border border-white/20 text-white text-[10px] font-bold uppercase tracking-[0.2em] py-3 px-4 rounded hover:bg-[#d4af37] hover:text-black transition-colors"
          >
            {model.stage === RevealStage.FullyClothed && "View Summer Outfit"}
            {model.stage === RevealStage.SummerOutfit && "View Swimwear"}
            {model.stage === RevealStage.Bikini && "Restart Sequence"}
          </button>
        </div>
      </div>

      {/* Stage Dots */}
      <div className="absolute top-4 right-4 flex gap-1.5 z-10">
         {[0, 1, 2].map(s => (
           <div 
            key={s} 
            className={`w-1.5 h-1.5 rounded-full transition-all duration-500 ${model.stage === s ? 'bg-[#d4af37] scale-125 shadow-[0_0_8px_rgba(212,175,55,1)]' : 'bg-white/30'}`}
           />
         ))}
      </div>
      
      {/* Tap to Change Hint */}
      {!isHovered && (
        <div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-[8px] font-bold text-white/40 uppercase tracking-[0.3em] bg-black/40 px-3 py-1 rounded-full backdrop-blur-sm">
          Tap to reveal
        </div>
      )}
    </div>
  );
};